server:
  port: 60002
  servlet:
    context-path: /api
spring:
  application:
    name: server
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  resources:
    static-locations: classpath:/templates/

# swagger配置
swagger:
  enabled: true