
server:
  port: 60002
  servlet:
    context-path: /demo
spring:
  application:
    name: demo
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  resources:
    static-locations: classpath:/templates/
  cloud:
    nacos:
      discovery:
        server-addr: https://nacos.haier.net
        group: HPRMC-DEV-TEST
  datasource:
    username:
    password:
    url: jdbc:mysql://10.250.2.24:3306/permission?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 100
      minimum-idle: 10
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    password: glecaoecduzbbgfb
    username: 1116309@qq.com
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
  cache:
    cache-names: permission
mybatis-plus:
  mapper-locations: classpath*:com/haier/**/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
    object-wrapper-factory: com.baomidou.mybatisplus.extension.MybatisMapWrapperFactory
    call-setters-on-nulls: true

rocketmq:
  acl:
    accessKey: hprmcRocketMQ
    accessSecret: 12345678
  consumer:
    groupName: hprmc-translate-permission-topic-test-consumer
    namesrvAddr: 10.250.36.5:9879;10.250.36.6:9879;10.250.36.7:9879;
    topics: hprmc-translate-permission-topic-test
    tags: S02022
    consumeThreadMin: 1
    consumeThreadMax: 1
    consumeMessageBatchMaxSize: 1

graph:
  restServerUrl: http://10.250.2.22:8080
  graphName: hugegraphdev
  username:
  password:
# swagger配置
swagger:
  enabled: true
system:
  code: S02022
  name: 权限中心

elasticsearch:
  ip: es-k8s.paas-test.haier.net
  port: 80
FastJsonAutoDiscoverable:
  autoDiscover: false;
# xxl job配置
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://hpc-schdule-test.paas-sit.haier.net/xxl-job-admin
    executor:
      address:
      appname: hprmc-permission-dev
      ip:
      logretentiondays: 30
      port: 12001
      logpath: /data/applogs/xxl-job/jobhandler
hac:
  webservice:
    user:
      group:
        add: http://hac.hoptest.haier.net:1027/com.haier.openplatform.hac.service.HacUserGroupServiceCli?wsdl
      privilege:
        add: http://hac.hoptest.haier.net:1030/com.haier.openplatform.hac.service.HacUserDataPrivilegeServiceCli?wsdl

# 应用行为中心 运行端配置
abm:
  clientId: 9f2485484bebb0388a8a24e793ba2b72
  clientKey: UzAyMDIy
  contact: hpctest@haier.net


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1